name: PHP Lint 🎳

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  test-php-cs-fixer:
    name: "PHP-CS-Fixer"
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: docker://oskarstark/php-cs-fixer-ga:2.19.0
      with:
        args: --config=.php_cs.dist --allow-risky=yes --dry-run --diff -- cadastre
